const airPorts = [
    {id:0,
    flightName:"BenGurion",
    country:"Japan",
    airPlanesFlights:1,
    availbleFlights:1,
},
    {id:1,
    flightName:"BenGurion1",
    country:"China",
    airPlanesFlights:2,
    availbleFlights:2,
},
    {id:2,
    flightName:"BenGurion2",
    country:"Israel",
    airPlanesFlights:3,
    availbleFlights:3,

},
    {id:3,
    flightName:"BenGurion3",
    country:"America",
    airPlanesFlights:4,
    availbleFlights:4,

},
    {id:4,
  flightName:"BenGurion4",
  country:"Canada",
  airPlanesFlights:5,
  availbleFlights:5,

},
    {id:5,
    flightName:"BenGurion5",
    country:"Italy",
    airPlanesFlights:6,
    availbleFlights:6,

},
    {id:6,
    flightName:"BenGurion6",
    country:"France",
    airPlanesFlights:7,
    availbleFlights:7,

},
    {id:7,
    flightName:"BenGurion7",
    country:"India",
    airPlanesFlights:8,
    availbleFlights:8,

},
    {id:8,
    flightName:"BenGurion8",
    country:"Iran",
    airPlanesFlights:9,
    availbleFlights:9,

},
    {id:9,
    flightName:"BenGurion9",
    country:"Sudan",
    airPlanesFlights:10,
    availbleFlights:10,

}]

module.exports = airPorts;
